/* ==========================================================================
   COPY
   --------------------------------------------------------------------------
   All site text, per language. Jokes are written natively in each language,
   not translated across, because a translated pun is a dead pun.

   House rule: no em dashes anywhere in this file. Commas, colons, periods
   and parentheses only.
   ========================================================================== */

window.PARTY_COPY = {

  /* ======================================================================
     ENGLISH
     ====================================================================== */
  en: {
    'meta.title': '03102 Introduction to Applied Celebration: Sirio’s Master’s Party',
    'meta.description': 'Course 03102, 5 ECTS. One evening minimum. Attendance is not mandatory but is strongly expected.',

    'nav.skip': 'Skip to main content',
    'nav.info': 'Course information',
    'nav.objectives': 'Learning objectives',
    'nav.enrol': 'Registration',
    'nav.location': 'Location',
    'nav.access': 'Building access',
    'nav.photos': 'Documentation',
    'nav.dept': 'Department of Graduation Studies',
    'nav.menu.open': 'Open the course menu',
    'nav.menu.close': 'Close the course menu',
    'nav.gallery': 'The album',
    'nav.index': 'Course index',

    'gallery.heading': 'The album',
    'gallery.lede': 'Everything submitted so far, newest first. Tap any photograph to open it.',
    'gallery.by': 'Submitted by {name}',
    'gallery.by.you': 'Submitted by you',
    'gallery.count.of': '{i} of {n}',
    'gallery.original': 'Open the full size',
    'gallery.close': 'Close the album viewer',
    'gallery.prev': 'Previous photograph',
    'gallery.next': 'Next photograph',
    'gallery.portal.t': 'The album',
    'gallery.portal.b': 'Everybody’s photographs, on a page of their own.',

    /* The standalone album page. Its own block, because it is its own page. */
    'album.back': 'The invitation',
    'album.eyebrow': 'Course 03102 · Documentation',
    'album.heading': 'The album',
    'album.lede': 'Everything handed in so far, newest first. Tap any photograph to open it.',
    'album.shuffle': 'Show me a random one',
    'album.addyours': 'Add yours',
    'album.loading': 'Retrieving the album.',
    'album.count.one': '1 photograph',
    'album.count.many': '{n} photographs',
    'album.open': 'Open the photograph submitted by {name}',
    'album.empty.t': 'Nothing here yet',
    'album.empty.b': 'The album fills up on the night. Come back once the evening has happened, or be the first to hand something in.',
    'album.failed.t': 'The album did not load',
    'album.failed.b': 'Check your connection and try again. Nothing you submitted is affected.',
    'album.foot': 'Course 03102. Photographs belong to whoever took them.',

    'photos.mine.one': 'Your submission',
    'photos.mine.many': 'Your {n} submissions',
    'photos.mine.open': 'Open your photograph {i}',
    'photos.mine.remove': 'Remove',
    'photos.mine.remove.aria': 'Remove your photograph {i} from the album',
    'photos.mine.confirm.q': 'Take this photograph out of the album? It goes for everyone, and it cannot be put back.',
    'photos.mine.confirm.yes': 'Remove the photograph',
    'photos.mine.confirm.no': 'Keep it in the album',
    'photos.mine.busy': 'Removing',
    'photos.mine.retry': 'Try removing it again',
    'photos.mine.removed': 'The photograph is out of the album.',
    'photos.mine.fail': 'It could not be removed. Nothing has changed.',
    'photos.mine.absent': 'Removals are not switched on yet. Nothing has changed, and the photograph is still in the album.',
    'photos.seealbum': 'See the whole album',

    'hero.eyebrow': 'Course 03102 · 5 ECTS · Autumn 2026',
    'hero.title': 'Introduction to Applied Celebration',
    'hero.cta.enrol': 'Register for the course',
    'hero.cta.location': 'Find the location',
    'hero.cta.access': 'Which door',
    'hero.deadline': 'Registration closes {date}',

    /* The course responsible. A real DTU course page names one and shows their
       face, so this one does too, and it is where the host's name lives on the
       page a guest actually looks at rather than only inside the fold. */
    'hero.host.role': 'Course responsible',

    /* The date itself is never written here. renderSaveDate builds it from
       config.startsAt through Intl, so the weekday and the month name come out
       right in this language without anyone maintaining them. */
    'savedate.eyebrow': 'Save the date',
    'savedate.cta': 'Add to your calendar',
    'savedate.google': 'or open it in Google Calendar',
    'savedate.event.title': 'Course 03102: Thesis Defended, Liver Pending',
    'savedate.event.body': 'Attendance is not mandatory but is strongly expected. Course description, registration and directions to the door:',
    'savedate.toast.ok': 'Calendar file saved. Open it to add the course.',
    'savedate.toast.fail': 'That did not work. Use the Google Calendar link instead.',

    'countdown.label': 'Time until first session',
    'countdown.days': 'days',
    'countdown.hours': 'hours',
    'countdown.minutes': 'minutes',
    'countdown.seconds': 'seconds',
    'countdown.live.label': 'Session status',
    'countdown.live.title': 'The course is now in session',
    'countdown.live.note': 'Late arrival is tolerated. Non arrival is noted.',
    'countdown.over.label': 'Session status',
    'countdown.over.title': 'The course has concluded',
    'countdown.over.note': 'Please submit your photographic documentation below.',

    'facts.heading': 'Course information',
    'facts.number': 'Course number',
    'facts.ects': 'Points (ECTS)',
    'facts.ects.value': '5 (not transferable)',
    'facts.type': 'Course type',
    'facts.type.value': 'MSc, mandatory',
    'facts.language': 'Language of instruction',
    'facts.language.value': 'Italian, English and Danish',
    'facts.duration': 'Duration',
    'facts.duration.value': 'One evening (minimum)',
    'facts.schedule': 'Scheduled',
    'facts.location': 'Location',
    'facts.location.tbd': 'To be announced',
    'facts.prereq': 'Prerequisites',
    'facts.prereq.value': 'None. Attendance at the actual defence was not required either.',
    'facts.responsible': 'Responsible',
    'facts.registration': 'Registration',
    'facts.registration.value': 'Required. Places are limited by the size of the room.',
    'facts.registration.link': 'Register here',
    'facts.deadline': 'Registration deadline',
    'facts.exam': 'Form of examination',
    'facts.exam.value': 'Continuous assessment, conducted informally',
    'facts.more': 'The full course description',

    'obj.heading': 'Learning objectives',
    'obj.intro': 'A student who has met the objectives of the course will be able to:',
    'obj.more': 'The six learning objectives',
    'obj.1': 'Locate the correct entrance to the building on the first attempt',
    'obj.2': 'Congratulate the host without asking what the thesis was about',
    'obj.3': 'Identify at least three people they have never met before',
    'obj.4': 'Operate a quiz interface under non ideal conditions',
    'obj.5': 'Document the evening photographically, within the stated upload limit',
    'obj.6': 'Assess their own capacity accurately, and act on that assessment',

    'enrol.heading': 'Course registration',
    'enrol.lede': 'Registration is required. Not for bureaucratic reasons, but because the host needs to know how much food to buy.',
    'enrol.pending.title': 'Registration opens shortly',
    'enrol.pending.body': 'The registration system is being set up. Come back in a few days, or tell the host directly in the meantime.',

    'enrol.form.name.label': 'Full name',
    'enrol.form.name.hint': 'As it should appear on the participant list.',
    'enrol.form.guests.label': 'People you are bringing',
    'enrol.form.guests.hint': 'You are already counted.',
    'enrol.form.note.label': 'Note to the host (optional)',
    'enrol.form.note.hint': 'Allergies, arrival time, anything else. Only the host reads this, and you can change it later.',

    /* Every one of these is 36 characters or fewer in every language. Not a
       style preference: at 320px a two line error would defeat the reserved
       error box and move the submit button out from under a thumb. */
    'enrol.err.nameRequired': 'Enter your name.',
    'enrol.err.nameLong': 'Use 60 characters or fewer.',
    'enrol.err.noteLong': 'Use 500 characters or fewer.',
    'enrol.err.guestsRange': 'Choose a number from the list.',

    'enrol.submit': 'Submit registration',
    'enrol.submitting': 'Submitting',
    'enrol.retry': 'Submit again',
    'enrol.update': 'Save changes',
    'enrol.cancel': 'Discard changes',
    'enrol.fail.title': 'The registration was not recorded.',
    'enrol.fail.body': 'Your answers are still here. Check your connection and submit again.',

    'enrol.success.title': 'Registration confirmed',
    'enrol.success.lede': 'You are on the participant list. The host has the numbers.',
    'enrol.success.group.pending': 'The course group chat is not set up yet. The link appears here when it is.',
    'enrol.success.amend': 'Change these details',

    'enrol.record.name': 'Name',
    'enrol.record.guests': 'Additional guests',
    'enrol.record.guests.none': 'None',
    'enrol.record.note': 'Note',

    'enrol.return.title': 'Your registration',
    'enrol.return.lede': 'Registered in the name of {name}. Nothing further is required.',
    'enrol.edit': 'Change your registration',
    'enrol.updated.toast': 'Registration updated.',
    'enrol.withdraw': 'Withdraw from the course',
    'enrol.withdraw.confirm.q': 'This removes you from the participant list. You can register again later.',
    'enrol.withdraw.confirm.yes': 'Confirm withdrawal',
    'enrol.withdraw.confirm.no': 'Keep my registration',
    'enrol.withdrawn.title': 'You are unregistered',
    'enrol.withdrawn.body': 'You are off the participant list. The numbers have been updated.',
    'enrol.withdrawn.again': 'Register again',
    'enrol.identity.clear': 'Forget my details on this device',
    'enrol.identity.cleared': 'Details removed from this device.',
    'enrol.amend.pending': 'Changes cannot be recorded yet. Tell the host directly. Your registration stays as it is.',

    /* Two labels rather than one sentence. The total counts plus ones and the
       name list does not, so the two figures visibly disagree; the labels are
       worded so they already mean different things instead of a sentence being
       written to reconcile them. A real fact table would not write one. */
    'enrol.proof.count.label': 'Expected attendance',
    'enrol.proof.list.label': 'Registered',

    'nudge.enrol.text': 'You have not registered yet.',
    'nudge.enrol.cta': 'Register',
    'nudge.enrol.soon': 'Registration closes in {n} days.',
    'nudge.enrol.last': 'Registration closes tomorrow.',
    'nudge.enrol.today': 'Registration closes today.',
    'nudge.group.text': 'You are registered. One thing left.',
    'nudge.group.cta': 'Join the group',
    'nudge.dismiss': 'Dismiss',

    'wa.heading': 'Course announcements',
    'wa.body': 'Practical updates go out in the group chat. Address changes, delays, and the occasional photograph.',
    'wa.cta': 'Join the WhatsApp group',

    'loc.heading': 'Location',
    'loc.lede': 'Course sessions are held at the address below. Directions open in your own map application.',
    'loc.pending.title': 'Venue under confirmation',
    'loc.pending.body': 'The room booking is still being negotiated. The address appears here as soon as it is fixed, and this page updates itself.',
    'loc.address': 'Address',
    'loc.copy': 'Copy address',
    'loc.copied': 'Copied',
    'loc.copied.toast': 'Address copied to clipboard.',
    'loc.copy.failed': 'Copy it by hand',
    'loc.copy.failed.toast': 'Copy blocked by the browser. The address is now selected.',
    'loc.google': 'Open in Google Maps',
    'loc.apple': 'Open in Apple Maps',
    'loc.maptitle': 'Map showing the party location',
    'loc.map.loading': 'Map loading. The address above works without it.',
    'loc.map.blocked': 'The map did not load. Use the address or the directions buttons above.',
    'loc.map.fallback': 'If the map does not show, the address and buttons above work without it.',

    'access.heading': 'Building access',
    'access.lede': 'The single most useful section on this page. Watch this before you arrive, or while standing outside wondering which door is the right one.',
    'access.pending.title': 'Access documentation pending',
    'access.pending.body': 'A short clip showing the correct door is being produced. Until then, ask the person who invited you, or follow the noise.',
    'access.dir.heading': 'Written directions',
    'access.dir.pending.title': 'Door instructions pending',
    'access.dir.pending.body': 'The exact entrance is being confirmed. The address and the map above already get you to the building.',
    'access.notes.heading': 'Practical notes',
    'access.video.heading': 'Door video',
    'access.back': 'Back to the map and address',

    /* Labels only. The values beside them come from config.js and are shown
       exactly as the host wrote them, in every language. */
    'notes.entrance': 'Entrance',
    'notes.floor': 'Floor',
    'notes.buzzer': 'Doorbell',
    'notes.parking': 'Parking',
    'notes.transit': 'Public transport',
    'notes.bring': 'What to bring',
    'notes.arrive': 'When to arrive',

    'photos.heading': 'Documentation',
    'photos.lede': 'Students are asked to submit photographic evidence of the evening. Maximum five per person, which is a limit chosen to protect everyone.',
    'photos.pending.title': 'Submission portal opens later',
    'photos.pending.body': 'Uploads open closer to the date. Nothing is required from you now.',
    'photos.closed.body': 'Uploads open on {when}. Nothing is required from you until then.',
    'photos.gate.title': 'Registered students only',
    'photos.gate.body': 'Photographic evidence is accepted from registered students, so the album knows whose evening it was. Registration is one field.',
    'photos.cta': 'Submit photographs',
    'photos.remaining.label': 'Submissions remaining',
    'photos.zone.hint': 'or drop them here',
    'photos.rules.files': '{n} files',
    'photos.rules.photo': 'photos up to {mb} MB',
    'photos.rules.video': 'one may be a video',
    'photos.rules.seconds': '{n} seconds',
    'photos.rules.videosize': 'up to {mb} MB',
    'photos.permanent': 'Anything you submit goes into the album for everyone. You can take your own back from the row below. Nobody else can.',
    'photos.status.preparing': 'Preparing {i} of {n}',
    'photos.status.uploading': 'Sending {i} of {n}',
    'photos.status.done.one': 'One photograph is on record.',
    'photos.status.done.many': '{n} photographs are on record.',
    'photos.status.partial': '{ok} recorded, {bad} not.',
    'photos.queue.waiting': 'Queued',
    'photos.queue.preparing': 'Preparing',
    'photos.queue.uploading': 'Sending',
    'photos.queue.recording': 'Recording',
    'photos.queue.done': 'On record',
    'photos.queue.refused': 'Not accepted',
    'photos.queue.failed': 'Not sent',
    'photos.queue.unnamed': 'Untitled image',
    'photos.err.type': 'Not an image file',
    'photos.err.size': 'Larger than {mb} MB',
    'photos.err.empty': 'The file is empty',
    'photos.err.decode': 'This image could not be read',
    'photos.err.encode': 'Too large for this phone',
    'photos.err.network': 'The connection dropped',
    'photos.err.server': 'The archive refused it',
    'photos.refuse.extra': 'Five per person is the limit. {n} of these were not accepted.',
    'photos.refuse.server': 'The register already holds five in your name. This one was not added.',
    'photos.full.title': 'Documentation complete',
    'photos.full.body': 'Five photographs are on record in your name. The limit protects everyone, and at five you are protected.',
    'photos.retry.failed': 'Send the failed ones again',
    'photos.album.loading': 'Retrieving submissions.',
    'photos.album.empty': 'No submissions on record.',
    'photos.album.count.one': 'One submission on record.',
    'photos.album.count.many': '{n} submissions on record.',
    'photos.album.open': 'Open the photograph submitted by {name}.',

    'footer.disclaimer': 'A personal invitation, in the visual style of a university the host actually attended. Not affiliated with, endorsed by, or in any way the responsibility of that university.',
    'footer.built': 'Built for one evening in October.',
    'footer.lang': 'Language',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

  /* ======================================================================
     ITALIANO
     ====================================================================== */
  it: {
    'meta.title': '03102 Introduzione alla Celebrazione Applicata: la laurea magistrale di Sirio',
    'meta.description': 'Corso 03102, 5 CFU. Durata una serata minimo. La presenza non è obbligatoria ma è data per scontata.',

    'nav.skip': 'Vai al contenuto principale',
    'nav.info': 'Informazioni sul corso',
    'nav.objectives': 'Obiettivi formativi',
    'nav.enrol': 'Iscrizione',
    'nav.location': 'Sede',
    'nav.access': 'Accesso',
    'nav.photos': 'Documentazione',
    'nav.dept': 'Dipartimento di Studi Post Laurea',
    'nav.menu.open': 'Apri il menu del corso',
    'nav.menu.close': 'Chiudi il menu del corso',
    'nav.gallery': 'Album',
    'nav.index': 'Indice del corso',

    'gallery.heading': 'Album',
    'gallery.lede': 'Tutto quello che è stato caricato, dalla più recente. Tocca una foto per aprirla.',
    'gallery.by': 'Caricata da {name}',
    'gallery.by.you': 'Caricata da te',
    'gallery.count.of': '{i} di {n}',
    'gallery.original': 'Apri a dimensione piena',
    'gallery.close': 'Chiudi il visualizzatore',
    'gallery.prev': 'Foto precedente',
    'gallery.next': 'Foto successiva',
    'gallery.portal.t': 'L’album',
    'gallery.portal.b': 'Le foto di tutti, su una pagina tutta loro.',

    'album.back': 'L’invito',
    'album.eyebrow': 'Corso 03102 · Documentazione',
    'album.heading': 'L’album',
    'album.lede': 'Tutto quello che è stato consegnato, dalla più recente. Tocca una foto per aprirla.',
    'album.shuffle': 'Mostramene una a caso',
    'album.addyours': 'Aggiungi le tue',
    'album.loading': 'Recupero dell’album.',
    'album.count.one': '1 foto',
    'album.count.many': '{n} foto',
    'album.open': 'Apri la foto consegnata da {name}',
    'album.empty.t': 'Qui non c’è ancora niente',
    'album.empty.b': 'L’album si riempie durante la serata. Torna quando sarà successa, oppure sii il primo a consegnare qualcosa.',
    'album.failed.t': 'L’album non si è caricato',
    'album.failed.b': 'Controlla la connessione e riprova. Quello che hai consegnato non è stato toccato.',
    'album.foot': 'Corso 03102. Le foto appartengono a chi le ha scattate.',

    'photos.mine.one': 'La tua foto',
    'photos.mine.many': 'Le tue {n} foto',
    'photos.mine.open': 'Apri la tua foto {i}',
    'photos.mine.remove': 'Ritira',
    'photos.mine.remove.aria': 'Ritira la tua foto {i} dall’album',
    'photos.mine.confirm.q': 'Vuoi togliere questa foto dall’album? Sparisce per tutti e non si rimette.',
    'photos.mine.confirm.yes': 'Togli la foto',
    'photos.mine.confirm.no': 'Lasciala nell’album',
    'photos.mine.busy': 'Rimozione in corso',
    'photos.mine.retry': 'Prova a toglierla di nuovo',
    'photos.mine.removed': 'La foto non è più nell’album.',
    'photos.mine.fail': 'Non è stato possibile toglierla. Non è cambiato nulla.',
    'photos.mine.absent': 'I ritiri non sono ancora attivi. Non è cambiato nulla e la foto è ancora nell’album.',
    'photos.seealbum': 'Guarda tutte le foto',

    'hero.eyebrow': 'Corso 03102 · 5 CFU · Autunno 2026',
    'hero.title': 'Introduzione alla Celebrazione Applicata',
    'hero.cta.enrol': 'Iscriviti al corso',
    'hero.cta.location': 'Trova la sede',
    'hero.cta.access': 'Quale porta',
    'hero.deadline': 'Le iscrizioni chiudono il {date}',

    'hero.host.role': 'Responsabile del corso',

    'savedate.eyebrow': 'Segna la data',
    'savedate.cta': 'Aggiungi al calendario',
    'savedate.google': 'oppure aprilo in Google Calendar',
    'savedate.event.title': 'Corso 03102: Thesis Defended, Liver Pending',
    'savedate.event.body': 'La presenza non è obbligatoria ma è caldamente prevista. Descrizione del corso, iscrizione e indicazioni per la porta giusta:',
    'savedate.toast.ok': 'File del calendario salvato. Aprilo per aggiungere il corso.',
    'savedate.toast.fail': 'Non ha funzionato. Usa il link a Google Calendar.',

    'countdown.label': 'Tempo alla prima lezione',
    'countdown.days': 'giorni',
    'countdown.hours': 'ore',
    'countdown.minutes': 'minuti',
    'countdown.seconds': 'secondi',
    'countdown.live.label': 'Stato della lezione',
    'countdown.live.title': 'Il corso è in corso',
    'countdown.live.note': 'Il ritardo è tollerato. L’assenza viene registrata.',
    'countdown.over.label': 'Stato della lezione',
    'countdown.over.title': 'Il corso è terminato',
    'countdown.over.note': 'Si prega di consegnare la documentazione fotografica qui sotto.',

    'facts.heading': 'Informazioni sul corso',
    'facts.number': 'Numero del corso',
    'facts.ects': 'Crediti (CFU)',
    'facts.ects.value': '5 (non riconosciuti)',
    'facts.type': 'Tipo di corso',
    'facts.type.value': 'Magistrale, obbligatorio',
    'facts.language': 'Lingua di insegnamento',
    'facts.language.value': 'Italiano, inglese e danese',
    'facts.duration': 'Durata',
    'facts.duration.value': 'Una serata (minimo)',
    'facts.schedule': 'Orario',
    'facts.location': 'Sede',
    'facts.location.tbd': 'Da comunicare',
    'facts.prereq': 'Prerequisiti',
    'facts.prereq.value': 'Nessuno. Non era richiesta la presenza nemmeno alla discussione.',
    'facts.responsible': 'Responsabile',
    'facts.registration': 'Iscrizione',
    'facts.registration.value': 'Obbligatoria. I posti sono limitati dalle dimensioni della stanza.',
    'facts.registration.link': 'Iscriviti qui',
    'facts.deadline': 'Scadenza iscrizioni',
    'facts.exam': 'Modalità di esame',
    'facts.exam.value': 'Valutazione continua, condotta in modo informale',
    'facts.more': 'La descrizione completa del corso',

    'obj.heading': 'Obiettivi formativi',
    'obj.intro': 'Lo studente che ha raggiunto gli obiettivi del corso sarà in grado di:',
    'obj.more': 'I sei obiettivi formativi',
    'obj.1': 'Individuare l’ingresso corretto dell’edificio al primo tentativo',
    'obj.2': 'Congratularsi con il festeggiato senza chiedere di cosa parlasse la tesi',
    'obj.3': 'Riconoscere almeno tre persone mai viste prima',
    'obj.4': 'Utilizzare un quiz interattivo in condizioni non ideali',
    'obj.5': 'Documentare fotograficamente la serata, entro il limite indicato',
    'obj.6': 'Valutare correttamente le proprie capacità, e regolarsi di conseguenza',

    'enrol.heading': 'Iscrizione al corso',
    'enrol.lede': 'L’iscrizione è obbligatoria. Non per motivi burocratici, ma perché il festeggiato deve sapere quanto cibo comprare.',
    'enrol.pending.title': 'Le iscrizioni aprono a breve',
    'enrol.pending.body': 'Il sistema di iscrizione è in fase di configurazione. Torna tra qualche giorno, oppure dillo direttamente al festeggiato.',

    'enrol.form.name.label': 'Nome e cognome',
    'enrol.form.name.hint': 'Come deve comparire nell’elenco dei partecipanti.',
    'enrol.form.guests.label': 'Persone che porti con te',
    'enrol.form.guests.hint': 'Tu sei già incluso nel conteggio.',
    'enrol.form.note.label': 'Nota per il festeggiato (facoltativa)',
    'enrol.form.note.hint': 'Allergie, orario di arrivo, qualsiasi altra cosa. La legge solo il festeggiato, e puoi modificarla più tardi.',

    'enrol.err.nameRequired': 'Inserisci il tuo nome.',
    'enrol.err.nameLong': 'Usa al massimo 60 caratteri.',
    'enrol.err.noteLong': 'Usa al massimo 500 caratteri.',
    'enrol.err.guestsRange': 'Scegli un numero dall’elenco.',

    'enrol.submit': 'Invia l’iscrizione',
    'enrol.submitting': 'Invio in corso',
    'enrol.retry': 'Invia di nuovo',
    'enrol.update': 'Salva le modifiche',
    'enrol.cancel': 'Annulla le modifiche',
    'enrol.fail.title': 'L’iscrizione non è stata registrata.',
    'enrol.fail.body': 'Le tue risposte sono ancora qui. Controlla la connessione e invia di nuovo.',

    'enrol.success.title': 'Iscrizione confermata',
    'enrol.success.lede': 'Sei nell’elenco dei partecipanti. Il festeggiato ha i numeri.',
    'enrol.success.group.pending': 'Il gruppo del corso non è ancora attivo. Il link comparirà qui quando lo sarà.',
    'enrol.success.amend': 'Modifica questi dati',

    'enrol.record.name': 'Nome',
    'enrol.record.guests': 'Ospiti aggiuntivi',
    'enrol.record.guests.none': 'Nessuno',
    'enrol.record.note': 'Nota',

    'enrol.return.title': 'La tua iscrizione',
    'enrol.return.lede': 'Iscrizione a nome di {name}. Non serve altro.',
    'enrol.edit': 'Modifica l’iscrizione',
    'enrol.updated.toast': 'Iscrizione aggiornata.',
    'enrol.withdraw': 'Ritirati dal corso',
    'enrol.withdraw.confirm.q': 'Questo ti toglie dall’elenco dei partecipanti. Puoi iscriverti di nuovo più tardi.',
    'enrol.withdraw.confirm.yes': 'Conferma il ritiro',
    'enrol.withdraw.confirm.no': 'Mantieni l’iscrizione',
    'enrol.withdrawn.title': 'Iscrizione ritirata',
    'enrol.withdrawn.body': 'Non sei più nell’elenco dei partecipanti. I numeri sono stati aggiornati.',
    'enrol.withdrawn.again': 'Iscriviti di nuovo',
    'enrol.identity.clear': 'Dimentica i miei dati su questo dispositivo',
    'enrol.identity.cleared': 'Dati rimossi da questo dispositivo.',
    'enrol.amend.pending': 'Le modifiche non possono ancora essere registrate. Dillo direttamente al festeggiato. La tua iscrizione resta com’è.',

    'enrol.proof.count.label': 'Presenze previste',
    'enrol.proof.list.label': 'Iscritti',

    'nudge.enrol.text': 'Non ti sei ancora iscritto.',
    'nudge.enrol.cta': 'Iscriviti',
    'nudge.enrol.soon': 'Le iscrizioni chiudono tra {n} giorni.',
    'nudge.enrol.last': 'Le iscrizioni chiudono domani.',
    'nudge.enrol.today': 'Le iscrizioni chiudono oggi.',
    'nudge.group.text': 'Sei iscritto. Manca una cosa sola.',
    'nudge.group.cta': 'Entra nel gruppo',
    'nudge.dismiss': 'Chiudi',

    'wa.heading': 'Comunicazioni del corso',
    'wa.body': 'Gli aggiornamenti pratici passano dal gruppo. Cambi di indirizzo, ritardi, e qualche fotografia.',
    'wa.cta': 'Entra nel gruppo WhatsApp',

    'loc.heading': 'Sede',
    'loc.lede': 'Le lezioni si tengono all’indirizzo qui sotto. Le indicazioni si aprono nella tua applicazione di mappe.',
    'loc.pending.title': 'Sede in via di conferma',
    'loc.pending.body': 'La prenotazione dell’aula è ancora in trattativa. L’indirizzo compare qui appena è confermato, e la pagina si aggiorna da sola.',
    'loc.address': 'Indirizzo',
    'loc.copy': 'Copia indirizzo',
    'loc.copied': 'Copiato',
    'loc.copied.toast': 'Indirizzo copiato negli appunti.',
    'loc.copy.failed': 'Copialo a mano',
    'loc.copy.failed.toast': 'Copia bloccata dal browser. L’indirizzo è ora selezionato.',
    'loc.google': 'Apri in Google Maps',
    'loc.apple': 'Apri in Apple Maps',
    'loc.maptitle': 'Mappa con la sede della festa',
    'loc.map.loading': 'Mappa in caricamento. L’indirizzo qui sopra funziona anche senza.',
    'loc.map.blocked': 'La mappa non si è caricata. Usa l’indirizzo o i pulsanti qui sopra.',
    'loc.map.fallback': 'Se la mappa non compare, l’indirizzo e i pulsanti qui sopra funzionano lo stesso.',

    'access.heading': 'Accesso all’edificio',
    'access.lede': 'La sezione più utile di questa pagina. Guardala prima di arrivare, oppure mentre sei fuori a chiederti quale sia la porta giusta.',
    'access.pending.title': 'Documentazione di accesso in preparazione',
    'access.pending.body': 'Un breve video che mostra la porta corretta è in produzione. Nel frattempo, chiedi a chi ti ha invitato, o segui il rumore.',
    'access.dir.heading': 'Indicazioni scritte',
    'access.dir.pending.title': 'Istruzioni per la porta in arrivo',
    'access.dir.pending.body': 'L’ingresso esatto è in via di conferma. L’indirizzo e la mappa qui sopra ti portano comunque all’edificio.',
    'access.notes.heading': 'Note pratiche',
    'access.video.heading': 'Video della porta',
    'access.back': 'Torna alla mappa e all’indirizzo',

    'notes.entrance': 'Ingresso',
    'notes.floor': 'Piano',
    'notes.buzzer': 'Campanello',
    'notes.parking': 'Parcheggio',
    'notes.transit': 'Mezzi pubblici',
    'notes.bring': 'Cosa portare',
    'notes.arrive': 'Quando arrivare',

    'photos.heading': 'Documentazione',
    'photos.lede': 'Agli studenti è richiesto di consegnare prove fotografiche della serata. Massimo cinque a testa, un limite scelto per tutelare tutti.',
    'photos.pending.title': 'Il portale di consegna apre più avanti',
    'photos.pending.body': 'I caricamenti si aprono a ridosso della data. Per ora non devi fare nulla.',
    'photos.closed.body': 'I caricamenti si aprono il {when}. Fino ad allora non devi fare nulla.',
    'photos.gate.title': 'Solo studenti iscritti',
    'photos.gate.body': 'Le prove fotografiche si accettano dagli studenti iscritti, così l’album sa di chi è la serata. L’iscrizione è un campo solo.',
    'photos.cta': 'Consegna le fotografie',
    'photos.remaining.label': 'Consegne rimanenti',
    'photos.zone.hint': 'oppure trascinale qui',
    'photos.rules.files': '{n} file',
    'photos.rules.photo': 'foto fino a {mb} MB',
    'photos.rules.video': 'uno può essere un video',
    'photos.rules.seconds': '{n} secondi',
    'photos.rules.videosize': 'fino a {mb} MB',
    'photos.permanent': 'Quello che consegni finisce nell’album, visibile a tutti. Le tue puoi ritirarle dalla fila qui sotto. Quelle degli altri no.',
    'photos.status.preparing': 'Preparazione {i} di {n}',
    'photos.status.uploading': 'Invio {i} di {n}',
    'photos.status.done.one': 'Una fotografia è agli atti.',
    'photos.status.done.many': '{n} fotografie sono agli atti.',
    'photos.status.partial': '{ok} registrate, {bad} no.',
    'photos.queue.waiting': 'In coda',
    'photos.queue.preparing': 'In preparazione',
    'photos.queue.uploading': 'Invio',
    'photos.queue.recording': 'Registrazione',
    'photos.queue.done': 'Agli atti',
    'photos.queue.refused': 'Non accettata',
    'photos.queue.failed': 'Non inviata',
    'photos.queue.unnamed': 'Immagine senza nome',
    'photos.err.type': 'Non è un’immagine',
    'photos.err.size': 'Più di {mb} MB',
    'photos.err.empty': 'Il file è vuoto',
    'photos.err.decode': 'Immagine illeggibile',
    'photos.err.encode': 'Troppo grande per il telefono',
    'photos.err.network': 'Connessione interrotta',
    'photos.err.server': 'L’archivio l’ha rifiutata',
    'photos.refuse.extra': 'Il limite è cinque a testa. {n} di queste non sono state accettate.',
    'photos.refuse.server': 'Il registro ha già cinque fotografie a tuo nome. Questa non è stata aggiunta.',
    'photos.full.title': 'Documentazione completa',
    'photos.full.body': 'Cinque fotografie risultano a tuo nome. Il limite tutela tutti, e a cinque sei ufficialmente tutelato.',
    'photos.retry.failed': 'Invia di nuovo quelle non riuscite',
    'photos.album.loading': 'Recupero delle consegne.',
    'photos.album.empty': 'Nessuna consegna agli atti.',
    'photos.album.count.one': 'Una consegna agli atti.',
    'photos.album.count.many': '{n} consegne agli atti.',
    'photos.album.open': 'Apri la fotografia consegnata da {name}.',

    'footer.disclaimer': 'Un invito personale, nello stile grafico di un’università che il festeggiato ha davvero frequentato. Non affiliato, non approvato e in nessun modo responsabilità di tale università.',
    'footer.built': 'Fatto per una sera di ottobre.',
    'footer.lang': 'Lingua',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

  /* ======================================================================
     DANSK
     ----------------------------------------------------------------------
     A full language, not a joke. The classmates this parody is aimed at
     are Danish, and the CourseBase vocabulary (skemaplacering, læringsmål,
     kursusansvarlig) is the part they will actually recognise.
     ====================================================================== */
  da: {
    'meta.title': '03102 Introduktion til Anvendt Fejring: Sirios kandidatfest',
    'meta.description': 'Kursus 03102, 5 ECTS. Varighed én aften minimum. Fremmøde er ikke obligatorisk, men forventes.',

    'nav.skip': 'Gå til hovedindhold',
    'nav.info': 'Kursusinformation',
    'nav.objectives': 'Læringsmål',
    'nav.enrol': 'Tilmelding',
    'nav.location': 'Sted',
    'nav.access': 'Adgang',   // short on purpose: this is the one nav item kept on phones
    'nav.photos': 'Dokumentation',
    'nav.dept': 'Institut for Kandidatstudier',
    'nav.menu.open': 'Åbn kursusmenuen',
    'nav.menu.close': 'Luk kursusmenuen',
    'nav.gallery': 'Albummet',
    'nav.index': 'Kursusindeks',

    'gallery.heading': 'Albummet',
    'gallery.lede': 'Alt hvad der er uploadet indtil nu, nyeste først. Tryk på et billede for at åbne det.',
    'gallery.by': 'Uploadet af {name}',
    'gallery.by.you': 'Uploadet af dig',
    'gallery.count.of': '{i} af {n}',
    'gallery.original': 'Åbn i fuld størrelse',
    'gallery.close': 'Luk billedvisningen',
    'gallery.prev': 'Forrige billede',
    'gallery.next': 'Næste billede',
    'gallery.portal.t': 'Albummet',
    'gallery.portal.b': 'Alles billeder, på deres egen side.',

    'album.back': 'Invitationen',
    'album.eyebrow': 'Kursus 03102 · Dokumentation',
    'album.heading': 'Albummet',
    'album.lede': 'Alt der er afleveret indtil nu, nyeste først. Tryk på et billede for at åbne det.',
    'album.shuffle': 'Vis mig et tilfældigt',
    'album.addyours': 'Tilføj dine',
    'album.loading': 'Henter albummet.',
    'album.count.one': '1 billede',
    'album.count.many': '{n} billeder',
    'album.open': 'Åbn billedet afleveret af {name}',
    'album.empty.t': 'Her er ikke noget endnu',
    'album.empty.b': 'Albummet fyldes op om aftenen. Kom tilbage når den har fundet sted, eller vær den første til at aflevere noget.',
    'album.failed.t': 'Albummet blev ikke hentet',
    'album.failed.b': 'Tjek din forbindelse, og prøv igen. Det du har afleveret, er ikke berørt.',
    'album.foot': 'Kursus 03102. Billederne tilhører dem, der har taget dem.',

    'photos.mine.one': 'Dit billede',
    'photos.mine.many': 'Dine {n} billeder',
    'photos.mine.open': 'Åbn dit billede {i}',
    'photos.mine.remove': 'Fjern',
    'photos.mine.remove.aria': 'Fjern dit billede {i} fra albummet',
    'photos.mine.confirm.q': 'Skal dette billede ud af albummet? Det forsvinder for alle, og det kan ikke sættes tilbage.',
    'photos.mine.confirm.yes': 'Fjern billedet',
    'photos.mine.confirm.no': 'Behold det i albummet',
    'photos.mine.busy': 'Fjerner',
    'photos.mine.retry': 'Prøv at fjerne det igen',
    'photos.mine.removed': 'Billedet er ude af albummet.',
    'photos.mine.fail': 'Det kunne ikke fjernes. Intet er ændret.',
    'photos.mine.absent': 'Fjernelse er ikke slået til endnu. Intet er ændret, og billedet ligger stadig i albummet.',
    'photos.seealbum': 'Se hele albummet',

    'hero.eyebrow': 'Kursus 03102 · 5 ECTS · Efterår 2026',
    'hero.title': 'Introduktion til Anvendt Fejring',
    'hero.cta.enrol': 'Tilmeld dig kurset',
    'hero.cta.location': 'Find stedet',
    'hero.cta.access': 'Hvilken dør',
    'hero.deadline': 'Tilmelding lukker {date}',

    'hero.host.role': 'Kursusansvarlig',

    'savedate.eyebrow': 'Sæt kryds i kalenderen',
    'savedate.cta': 'Tilføj til din kalender',
    'savedate.google': 'eller åbn den i Google Kalender',
    'savedate.event.title': 'Kursus 03102: Thesis Defended, Liver Pending',
    'savedate.event.body': 'Fremmøde er ikke obligatorisk, men forventes kraftigt. Kursusbeskrivelse, tilmelding og vejvisning til den rigtige dør:',
    'savedate.toast.ok': 'Kalenderfilen er gemt. Åbn den for at tilføje kurset.',
    'savedate.toast.fail': 'Det virkede ikke. Brug linket til Google Kalender i stedet.',

    'countdown.label': 'Tid til første undervisningsgang',
    'countdown.days': 'dage',
    'countdown.hours': 'timer',
    'countdown.minutes': 'minutter',
    'countdown.seconds': 'sekunder',
    'countdown.live.label': 'Undervisningsstatus',
    'countdown.live.title': 'Undervisningen er i gang',
    'countdown.live.note': 'Forsinkelse tolereres. Udeblivelse noteres.',
    'countdown.over.label': 'Undervisningsstatus',
    'countdown.over.title': 'Kurset er afsluttet',
    'countdown.over.note': 'Aflever venligst din fotodokumentation nedenfor.',

    'facts.heading': 'Kursusinformation',
    'facts.number': 'Kursusnummer',
    'facts.ects': 'Point (ECTS)',
    'facts.ects.value': '5 (kan ikke overføres)',
    'facts.type': 'Kursustype',
    'facts.type.value': 'Kandidat, obligatorisk',
    'facts.language': 'Undervisningssprog',
    'facts.language.value': 'Italiensk, engelsk og dansk',
    'facts.duration': 'Varighed',
    'facts.duration.value': 'Én aften (minimum)',
    'facts.schedule': 'Skemaplacering',
    'facts.location': 'Sted',
    'facts.location.tbd': 'Oplyses senere',
    'facts.prereq': 'Forudsætninger',
    'facts.prereq.value': 'Ingen. Fremmøde ved selve forsvaret var heller ikke påkrævet.',
    'facts.exam': 'Eksamensform',
    'facts.exam.value': 'Løbende evaluering, gennemført uformelt',
    'facts.more': 'Hele kursusbeskrivelsen',
    'facts.responsible': 'Kursusansvarlig',
    'facts.registration': 'Tilmelding',
    'facts.registration.value': 'Påkrævet. Antallet af pladser er begrænset af lokalets størrelse.',
    'facts.registration.link': 'Tilmeld dig her',
    'facts.deadline': 'Tilmeldingsfrist',

    'obj.heading': 'Læringsmål',
    'obj.intro': 'En studerende, der har opfyldt kursets mål, vil kunne:',
    'obj.more': 'De seks læringsmål',
    'obj.1': 'Finde den rigtige indgang til bygningen i første forsøg',
    'obj.2': 'Lykønske værten uden at spørge, hvad specialet handlede om',
    'obj.3': 'Identificere mindst tre personer, som vedkommende aldrig har mødt før',
    'obj.4': 'Betjene en quiz under ikke ideelle forhold',
    'obj.5': 'Dokumentere aftenen fotografisk inden for den angivne grænse',
    'obj.6': 'Vurdere sin egen kapacitet korrekt og handle derefter',

    'enrol.heading': 'Tilmelding til kurset',
    'enrol.lede': 'Tilmelding er påkrævet. Ikke af bureaukratiske årsager, men fordi værten skal vide, hvor meget mad der skal købes.',
    'enrol.pending.title': 'Tilmelding åbner snart',
    'enrol.pending.body': 'Tilmeldingssystemet er ved at blive sat op. Kom tilbage om et par dage, eller sig det direkte til værten i mellemtiden.',

    'enrol.form.name.label': 'Fulde navn',
    'enrol.form.name.hint': 'Som det skal stå på deltagerlisten.',
    'enrol.form.guests.label': 'Personer du tager med',
    'enrol.form.guests.hint': 'Du selv tæller allerede med.',
    'enrol.form.note.label': 'Besked til værten (valgfri)',
    'enrol.form.note.hint': 'Allergier, ankomsttidspunkt eller andet. Kun værten læser den, og du kan ændre den senere.',

    'enrol.err.nameRequired': 'Skriv dit navn.',
    'enrol.err.nameLong': 'Brug højst 60 tegn.',
    'enrol.err.noteLong': 'Brug højst 500 tegn.',
    'enrol.err.guestsRange': 'Vælg et tal fra listen.',

    'enrol.submit': 'Send tilmelding',
    'enrol.submitting': 'Sender',
    'enrol.retry': 'Send igen',
    'enrol.update': 'Gem ændringer',
    'enrol.cancel': 'Kassér ændringer',
    'enrol.fail.title': 'Tilmeldingen blev ikke registreret.',
    'enrol.fail.body': 'Dine svar står der stadig. Tjek din forbindelse, og send igen.',

    'enrol.success.title': 'Tilmelding bekræftet',
    'enrol.success.lede': 'Du står på deltagerlisten. Værten har tallene.',
    'enrol.success.group.pending': 'Kursets gruppechat er ikke oprettet endnu. Linket kommer her, når den er.',
    'enrol.success.amend': 'Ret disse oplysninger',

    'enrol.record.name': 'Navn',
    'enrol.record.guests': 'Ekstra gæster',
    'enrol.record.guests.none': 'Ingen',
    'enrol.record.note': 'Besked',

    'enrol.return.title': 'Din tilmelding',
    'enrol.return.lede': 'Tilmeldt i navnet {name}. Der kræves ikke mere.',
    'enrol.edit': 'Ret din tilmelding',
    'enrol.updated.toast': 'Tilmeldingen er opdateret.',
    'enrol.withdraw': 'Meld dig fra kurset',
    'enrol.withdraw.confirm.q': 'Det fjerner dig fra deltagerlisten. Du kan tilmelde dig igen senere.',
    'enrol.withdraw.confirm.yes': 'Bekræft framelding',
    'enrol.withdraw.confirm.no': 'Behold min tilmelding',
    'enrol.withdrawn.title': 'Du er frameldt',
    'enrol.withdrawn.body': 'Du står ikke længere på deltagerlisten. Tallene er opdateret.',
    'enrol.withdrawn.again': 'Tilmeld dig igen',
    'enrol.identity.clear': 'Glem mine oplysninger på denne enhed',
    'enrol.identity.cleared': 'Oplysningerne er fjernet fra denne enhed.',
    'enrol.amend.pending': 'Ændringer kan ikke registreres endnu. Sig det direkte til værten. Din tilmelding står, som den er.',

    'enrol.proof.count.label': 'Forventet fremmøde',
    'enrol.proof.list.label': 'Tilmeldte',

    'nudge.enrol.text': 'Du har ikke tilmeldt dig endnu.',
    'nudge.enrol.cta': 'Tilmeld dig',
    'nudge.enrol.soon': 'Tilmelding lukker om {n} dage.',
    'nudge.enrol.last': 'Tilmelding lukker i morgen.',
    'nudge.enrol.today': 'Tilmelding lukker i dag.',
    'nudge.group.text': 'Du er tilmeldt. Én ting mangler.',
    'nudge.group.cta': 'Kom med i gruppen',
    'nudge.dismiss': 'Luk',

    'wa.heading': 'Kursusmeddelelser',
    'wa.body': 'Praktiske opdateringer sendes i gruppechatten. Adresseændringer, forsinkelser og et enkelt billede i ny og næ.',
    'wa.cta': 'Kom med i WhatsApp gruppen',

    'loc.heading': 'Sted',
    'loc.lede': 'Undervisningen finder sted på adressen nedenfor. Ruten åbner i din egen kortapp.',
    'loc.pending.title': 'Lokale afventer bekræftelse',
    'loc.pending.body': 'Lokalebookingen forhandles stadig. Adressen vises her, så snart den ligger fast, og siden opdaterer sig selv.',
    'loc.address': 'Adresse',
    'loc.copy': 'Kopiér adresse',
    'loc.copied': 'Kopieret',
    'loc.copied.toast': 'Adressen er kopieret til udklipsholderen.',
    'loc.copy.failed': 'Kopiér den manuelt',
    'loc.copy.failed.toast': 'Kopiering blev blokeret af browseren. Adressen er nu markeret.',
    'loc.google': 'Åbn i Google Maps',
    'loc.apple': 'Åbn i Apple Maps',
    'loc.maptitle': 'Kort der viser festens placering',
    'loc.map.loading': 'Kortet indlæses. Adressen ovenfor virker også uden.',
    'loc.map.blocked': 'Kortet blev ikke indlæst. Brug adressen eller knapperne ovenfor.',
    'loc.map.fallback': 'Hvis kortet ikke vises, virker adressen og knapperne ovenfor alligevel.',

    'access.heading': 'Adgang til bygningen',
    'access.lede': 'Den mest nyttige sektion på denne side. Se den, før du ankommer, eller mens du står udenfor og tænker over, hvilken dør der er den rigtige.',
    'access.pending.title': 'Adgangsdokumentation undervejs',
    'access.pending.body': 'Et kort klip, der viser den rigtige dør, er under produktion. Indtil da kan du spørge den, der inviterede dig, eller følge lyden.',
    'access.dir.heading': 'Skriftlig vejledning',
    'access.dir.pending.title': 'Døranvisning afventer',
    'access.dir.pending.body': 'Den præcise indgang er ved at blive bekræftet. Adressen og kortet ovenfor bringer dig alligevel hen til bygningen.',
    'access.notes.heading': 'Praktiske oplysninger',
    'access.video.heading': 'Dørvideo',
    'access.back': 'Tilbage til kort og adresse',

    'notes.entrance': 'Indgang',
    'notes.floor': 'Etage',
    'notes.buzzer': 'Dørtelefon',
    'notes.parking': 'Parkering',
    'notes.transit': 'Offentlig transport',
    'notes.bring': 'Hvad du skal medbringe',
    'notes.arrive': 'Hvornår du skal komme',

    'photos.heading': 'Dokumentation',
    'photos.lede': 'Studerende bedes aflevere fotografisk dokumentation af aftenen. Maksimalt fem per person, en grænse valgt for at beskytte alle.',
    'photos.pending.title': 'Afleveringsportalen åbner senere',
    'photos.pending.body': 'Upload åbner tættere på datoen. Du skal ikke gøre noget nu.',
    'photos.closed.body': 'Upload åbner {when}. Indtil da skal du ikke gøre noget.',
    'photos.gate.title': 'Kun tilmeldte studerende',
    'photos.gate.body': 'Fotografisk dokumentation modtages fra tilmeldte studerende, så albummet ved, hvis aften det var. Tilmelding er ét felt.',
    'photos.cta': 'Aflever fotografier',
    'photos.remaining.label': 'Resterende afleveringer',
    'photos.zone.hint': 'eller træk dem herind',
    'photos.rules.files': '{n} filer',
    'photos.rules.photo': 'billeder op til {mb} MB',
    'photos.rules.video': 'en må være en video',
    'photos.rules.seconds': '{n} sekunder',
    'photos.rules.videosize': 'op til {mb} MB',
    'photos.permanent': 'Det du afleverer, ligger i albummet og kan ses af alle. Dine egne kan du trække tilbage fra rækken herunder. Andres kan du ikke.',
    'photos.status.preparing': 'Forbereder {i} af {n}',
    'photos.status.uploading': 'Sender {i} af {n}',
    'photos.status.done.one': 'Ét fotografi er registreret.',
    'photos.status.done.many': '{n} fotografier er registreret.',
    'photos.status.partial': '{ok} registreret, {bad} ikke.',
    'photos.queue.waiting': 'I kø',
    'photos.queue.preparing': 'Forbereder',
    'photos.queue.uploading': 'Sender',
    'photos.queue.recording': 'Registrerer',
    'photos.queue.done': 'Registreret',
    'photos.queue.refused': 'Ikke modtaget',
    'photos.queue.failed': 'Ikke sendt',
    'photos.queue.unnamed': 'Billede uden navn',
    'photos.err.type': 'Ikke en billedfil',
    'photos.err.size': 'Større end {mb} MB',
    'photos.err.empty': 'Filen er tom',
    'photos.err.decode': 'Billedet kunne ikke læses',
    'photos.err.encode': 'For stort til denne telefon',
    'photos.err.network': 'Forbindelsen faldt ud',
    'photos.err.server': 'Arkivet afviste den',
    'photos.refuse.extra': 'Grænsen er fem per person. {n} af disse blev ikke modtaget.',
    'photos.refuse.server': 'Registret har allerede fem i dit navn. Denne blev ikke tilføjet.',
    'photos.full.title': 'Dokumentation fuldført',
    'photos.full.body': 'Fem fotografier er registreret i dit navn. Grænsen beskytter alle, og ved fem betragtes du som beskyttet.',
    'photos.retry.failed': 'Send de mislykkede igen',
    'photos.album.loading': 'Henter afleveringer.',
    'photos.album.empty': 'Ingen afleveringer registreret.',
    'photos.album.count.one': 'Én aflevering registreret.',
    'photos.album.count.many': '{n} afleveringer registreret.',
    'photos.album.open': 'Åbn fotografiet afleveret af {name}.',

    'footer.disclaimer': 'En personlig invitation i den grafiske stil fra et universitet, som værten faktisk har gået på. Ikke tilknyttet, ikke godkendt af og på ingen måde det pågældende universitets ansvar.',
    'footer.built': 'Lavet til én aften i oktober.',
    'footer.lang': 'Sprog',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

};
