/* ==========================================================================
   COPY
   --------------------------------------------------------------------------
   All site text, per language. Jokes are written natively in each language,
   not translated across, because a translated pun is a dead pun.

   House rule: no em dashes anywhere in this file. Commas, colons, periods
   and parentheses only.
   ========================================================================== */

window.PARTY_COPY = {

  /* ======================================================================
     ENGLISH
     ====================================================================== */
  en: {
    'meta.title': 'Course 03102: Thesis Defended, Liver Pending',
    'meta.description': 'Course 03102, 5 ECTS. One evening minimum. Attendance is not mandatory but is strongly expected.',

    'nav.skip': 'Skip to main content',
    'nav.info': 'Course information',
    'nav.objectives': 'Learning objectives',
    'nav.enrol': 'Registration',
    'nav.location': 'Location',
    'nav.access': 'Building access',
    'nav.photos': 'Documentation',
    'nav.dept': 'Department of Graduation Studies',

    'hero.eyebrow': 'Course 03102 · 5 ECTS · Autumn 2026',
    'hero.title': 'Thesis Defended, Liver Pending',
    'hero.cta.enrol': 'Register for the course',
    'hero.cta.location': 'Find the location',
    'hero.cta.access': 'Which door',
    'hero.deadline': 'Registration closes {date}',

    'countdown.label': 'Time until first session',
    'countdown.days': 'days',
    'countdown.hours': 'hours',
    'countdown.minutes': 'minutes',
    'countdown.seconds': 'seconds',
    'countdown.live.label': 'Session status',
    'countdown.live.title': 'The course is now in session',
    'countdown.live.note': 'Late arrival is tolerated. Non arrival is noted.',
    'countdown.over.label': 'Session status',
    'countdown.over.title': 'The course has concluded',
    'countdown.over.note': 'Please submit your photographic documentation below.',

    'facts.heading': 'Course information',
    'facts.number': 'Course number',
    'facts.ects': 'Points (ECTS)',
    'facts.ects.value': '5 (not transferable)',
    'facts.type': 'Course type',
    'facts.type.value': 'MSc, mandatory',
    'facts.language': 'Language of instruction',
    'facts.language.value': 'Italian, English and Danish',
    'facts.duration': 'Duration',
    'facts.duration.value': 'One evening (minimum)',
    'facts.schedule': 'Scheduled',
    'facts.location': 'Location',
    'facts.location.tbd': 'To be announced',
    'facts.prereq': 'Prerequisites',
    'facts.prereq.value': 'None. Attendance at the actual defence was not required either.',
    'facts.responsible': 'Responsible',
    'facts.registration': 'Registration',
    'facts.registration.value': 'Required. Places are limited by the size of the room.',
    'facts.registration.link': 'Register here',
    'facts.deadline': 'Registration deadline',
    'facts.exam': 'Form of examination',
    'facts.exam.value': 'Continuous assessment, conducted informally',

    'obj.heading': 'Learning objectives',
    'obj.intro': 'A student who has met the objectives of the course will be able to:',
    'obj.1': 'Locate the correct entrance to the building on the first attempt',
    'obj.2': 'Congratulate the host without asking what the thesis was about',
    'obj.3': 'Identify at least three people they have never met before',
    'obj.4': 'Operate a quiz interface under non ideal conditions',
    'obj.5': 'Document the evening photographically, within the stated upload limit',
    'obj.6': 'Assess their own capacity accurately, and act on that assessment',

    'enrol.heading': 'Course registration',
    'enrol.lede': 'Registration is required. Not for bureaucratic reasons, but because the host needs to know how much food to buy.',
    'enrol.pending.title': 'Registration opens shortly',
    'enrol.pending.body': 'The registration system is being set up. Come back in a few days, or tell the host directly in the meantime.',

    'nudge.enrol.text': 'You have not registered yet.',
    'nudge.enrol.cta': 'Register',
    'nudge.enrol.soon': 'Registration closes in {n} days.',
    'nudge.enrol.last': 'Registration closes tomorrow.',
    'nudge.enrol.today': 'Registration closes today.',
    'nudge.group.text': 'You are registered. One thing left.',
    'nudge.group.cta': 'Join the group',

    'wa.heading': 'Course announcements',
    'wa.body': 'Practical updates go out in the group chat. Address changes, delays, and the occasional photograph.',
    'wa.cta': 'Join the WhatsApp group',

    'loc.heading': 'Location',
    'loc.lede': 'Course sessions are held at the address below. Directions open in your own map application.',
    'loc.pending.title': 'Venue under confirmation',
    'loc.pending.body': 'The room booking is still being negotiated. The address appears here as soon as it is fixed, and this page updates itself.',
    'loc.address': 'Address',
    'loc.copy': 'Copy address',
    'loc.copied': 'Copied',
    'loc.copied.toast': 'Address copied to clipboard.',
    'loc.copy.failed': 'Copy it by hand',
    'loc.copy.failed.toast': 'Copy blocked by the browser. The address is now selected.',
    'loc.google': 'Open in Google Maps',
    'loc.apple': 'Open in Apple Maps',
    'loc.maptitle': 'Map showing the party location',
    'loc.map.loading': 'Map loading. The address above works without it.',
    'loc.map.blocked': 'The map did not load. Use the address or the directions buttons above.',

    'access.heading': 'Building access',
    'access.lede': 'The single most useful section on this page. Watch this before you arrive, or while standing outside wondering which door is the right one.',
    'access.pending.title': 'Access documentation pending',
    'access.pending.body': 'A short clip showing the correct door is being produced. Until then, ask the person who invited you, or follow the noise.',

    'photos.heading': 'Documentation',
    'photos.lede': 'Students are asked to submit photographic evidence of the evening. Maximum five per person, which is a limit chosen to protect everyone.',
    'photos.pending.title': 'Submission portal opens later',
    'photos.pending.body': 'Uploads open closer to the date. Nothing is required from you now.',

    'footer.disclaimer': 'A personal invitation, in the visual style of a university the host actually attended. Not affiliated with, endorsed by, or in any way the responsibility of that university.',
    'footer.built': 'Built for one evening in October.',
    'footer.lang': 'Language',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

  /* ======================================================================
     ITALIANO
     ====================================================================== */
  it: {
    'meta.title': 'Corso 03102: Thesis Defended, Liver Pending',
    'meta.description': 'Corso 03102, 5 CFU. Durata una serata minimo. La presenza non è obbligatoria ma è data per scontata.',

    'nav.skip': 'Vai al contenuto principale',
    'nav.info': 'Informazioni sul corso',
    'nav.objectives': 'Obiettivi formativi',
    'nav.enrol': 'Iscrizione',
    'nav.location': 'Sede',
    'nav.access': 'Accesso',
    'nav.photos': 'Documentazione',
    'nav.dept': 'Dipartimento di Studi Post Laurea',

    'hero.eyebrow': 'Corso 03102 · 5 CFU · Autunno 2026',
    'hero.title': 'Thesis Defended, Liver Pending',
    'hero.cta.enrol': 'Iscriviti al corso',
    'hero.cta.location': 'Trova la sede',
    'hero.cta.access': 'Quale porta',
    'hero.deadline': 'Le iscrizioni chiudono il {date}',

    'countdown.label': 'Tempo alla prima lezione',
    'countdown.days': 'giorni',
    'countdown.hours': 'ore',
    'countdown.minutes': 'minuti',
    'countdown.seconds': 'secondi',
    'countdown.live.label': 'Stato della lezione',
    'countdown.live.title': 'Il corso è in corso',
    'countdown.live.note': 'Il ritardo è tollerato. L’assenza viene registrata.',
    'countdown.over.label': 'Stato della lezione',
    'countdown.over.title': 'Il corso è terminato',
    'countdown.over.note': 'Si prega di consegnare la documentazione fotografica qui sotto.',

    'facts.heading': 'Informazioni sul corso',
    'facts.number': 'Numero del corso',
    'facts.ects': 'Crediti (CFU)',
    'facts.ects.value': '5 (non riconosciuti)',
    'facts.type': 'Tipo di corso',
    'facts.type.value': 'Magistrale, obbligatorio',
    'facts.language': 'Lingua di insegnamento',
    'facts.language.value': 'Italiano, inglese e danese',
    'facts.duration': 'Durata',
    'facts.duration.value': 'Una serata (minimo)',
    'facts.schedule': 'Orario',
    'facts.location': 'Sede',
    'facts.location.tbd': 'Da comunicare',
    'facts.prereq': 'Prerequisiti',
    'facts.prereq.value': 'Nessuno. Non era richiesta la presenza nemmeno alla discussione.',
    'facts.responsible': 'Responsabile',
    'facts.registration': 'Iscrizione',
    'facts.registration.value': 'Obbligatoria. I posti sono limitati dalle dimensioni della stanza.',
    'facts.registration.link': 'Iscriviti qui',
    'facts.deadline': 'Scadenza iscrizioni',
    'facts.exam': 'Modalità di esame',
    'facts.exam.value': 'Valutazione continua, condotta in modo informale',

    'obj.heading': 'Obiettivi formativi',
    'obj.intro': 'Lo studente che ha raggiunto gli obiettivi del corso sarà in grado di:',
    'obj.1': 'Individuare l’ingresso corretto dell’edificio al primo tentativo',
    'obj.2': 'Congratularsi con il festeggiato senza chiedere di cosa parlasse la tesi',
    'obj.3': 'Riconoscere almeno tre persone mai viste prima',
    'obj.4': 'Utilizzare un quiz interattivo in condizioni non ideali',
    'obj.5': 'Documentare fotograficamente la serata, entro il limite indicato',
    'obj.6': 'Valutare correttamente le proprie capacità, e regolarsi di conseguenza',

    'enrol.heading': 'Iscrizione al corso',
    'enrol.lede': 'L’iscrizione è obbligatoria. Non per motivi burocratici, ma perché il festeggiato deve sapere quanto cibo comprare.',
    'enrol.pending.title': 'Le iscrizioni aprono a breve',
    'enrol.pending.body': 'Il sistema di iscrizione è in fase di configurazione. Torna tra qualche giorno, oppure dillo direttamente al festeggiato.',

    'nudge.enrol.text': 'Non ti sei ancora iscritto.',
    'nudge.enrol.cta': 'Iscriviti',
    'nudge.enrol.soon': 'Le iscrizioni chiudono tra {n} giorni.',
    'nudge.enrol.last': 'Le iscrizioni chiudono domani.',
    'nudge.enrol.today': 'Le iscrizioni chiudono oggi.',
    'nudge.group.text': 'Sei iscritto. Manca una cosa sola.',
    'nudge.group.cta': 'Entra nel gruppo',

    'wa.heading': 'Comunicazioni del corso',
    'wa.body': 'Gli aggiornamenti pratici passano dal gruppo. Cambi di indirizzo, ritardi, e qualche fotografia.',
    'wa.cta': 'Entra nel gruppo WhatsApp',

    'loc.heading': 'Sede',
    'loc.lede': 'Le lezioni si tengono all’indirizzo qui sotto. Le indicazioni si aprono nella tua applicazione di mappe.',
    'loc.pending.title': 'Sede in via di conferma',
    'loc.pending.body': 'La prenotazione dell’aula è ancora in trattativa. L’indirizzo compare qui appena è confermato, e la pagina si aggiorna da sola.',
    'loc.address': 'Indirizzo',
    'loc.copy': 'Copia indirizzo',
    'loc.copied': 'Copiato',
    'loc.copied.toast': 'Indirizzo copiato negli appunti.',
    'loc.copy.failed': 'Copialo a mano',
    'loc.copy.failed.toast': 'Copia bloccata dal browser. L’indirizzo è ora selezionato.',
    'loc.google': 'Apri in Google Maps',
    'loc.apple': 'Apri in Apple Maps',
    'loc.maptitle': 'Mappa con la sede della festa',
    'loc.map.loading': 'Mappa in caricamento. L’indirizzo qui sopra funziona anche senza.',
    'loc.map.blocked': 'La mappa non si è caricata. Usa l’indirizzo o i pulsanti qui sopra.',

    'access.heading': 'Accesso all’edificio',
    'access.lede': 'La sezione più utile di questa pagina. Guardala prima di arrivare, oppure mentre sei fuori a chiederti quale sia la porta giusta.',
    'access.pending.title': 'Documentazione di accesso in preparazione',
    'access.pending.body': 'Un breve video che mostra la porta corretta è in produzione. Nel frattempo, chiedi a chi ti ha invitato, o segui il rumore.',

    'photos.heading': 'Documentazione',
    'photos.lede': 'Agli studenti è richiesto di consegnare prove fotografiche della serata. Massimo cinque a testa, un limite scelto per tutelare tutti.',
    'photos.pending.title': 'Il portale di consegna apre più avanti',
    'photos.pending.body': 'I caricamenti si aprono a ridosso della data. Per ora non devi fare nulla.',

    'footer.disclaimer': 'Un invito personale, nello stile grafico di un’università che il festeggiato ha davvero frequentato. Non affiliato, non approvato e in nessun modo responsabilità di tale università.',
    'footer.built': 'Fatto per una sera di ottobre.',
    'footer.lang': 'Lingua',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

  /* ======================================================================
     DANSK
     ----------------------------------------------------------------------
     A full language, not a joke. The classmates this parody is aimed at
     are Danish, and the CourseBase vocabulary (skemaplacering, læringsmål,
     kursusansvarlig) is the part they will actually recognise.
     ====================================================================== */
  da: {
    'meta.title': 'Kursus 03102: Thesis Defended, Liver Pending',
    'meta.description': 'Kursus 03102, 5 ECTS. Varighed én aften minimum. Fremmøde er ikke obligatorisk, men forventes.',

    'nav.skip': 'Gå til hovedindhold',
    'nav.info': 'Kursusinformation',
    'nav.objectives': 'Læringsmål',
    'nav.enrol': 'Tilmelding',
    'nav.location': 'Sted',
    'nav.access': 'Adgang',   // short on purpose: this is the one nav item kept on phones
    'nav.photos': 'Dokumentation',
    'nav.dept': 'Institut for Kandidatstudier',

    'hero.eyebrow': 'Kursus 03102 · 5 ECTS · Efterår 2026',
    'hero.title': 'Thesis Defended, Liver Pending',
    'hero.cta.enrol': 'Tilmeld dig kurset',
    'hero.cta.location': 'Find stedet',
    'hero.cta.access': 'Hvilken dør',
    'hero.deadline': 'Tilmelding lukker {date}',

    'countdown.label': 'Tid til første undervisningsgang',
    'countdown.days': 'dage',
    'countdown.hours': 'timer',
    'countdown.minutes': 'minutter',
    'countdown.seconds': 'sekunder',
    'countdown.live.label': 'Undervisningsstatus',
    'countdown.live.title': 'Undervisningen er i gang',
    'countdown.live.note': 'Forsinkelse tolereres. Udeblivelse noteres.',
    'countdown.over.label': 'Undervisningsstatus',
    'countdown.over.title': 'Kurset er afsluttet',
    'countdown.over.note': 'Aflever venligst din fotodokumentation nedenfor.',

    'facts.heading': 'Kursusinformation',
    'facts.number': 'Kursusnummer',
    'facts.ects': 'Point (ECTS)',
    'facts.ects.value': '5 (kan ikke overføres)',
    'facts.type': 'Kursustype',
    'facts.type.value': 'Kandidat, obligatorisk',
    'facts.language': 'Undervisningssprog',
    'facts.language.value': 'Italiensk, engelsk og dansk',
    'facts.duration': 'Varighed',
    'facts.duration.value': 'Én aften (minimum)',
    'facts.schedule': 'Skemaplacering',
    'facts.location': 'Sted',
    'facts.location.tbd': 'Oplyses senere',
    'facts.prereq': 'Forudsætninger',
    'facts.prereq.value': 'Ingen. Fremmøde ved selve forsvaret var heller ikke påkrævet.',
    'facts.exam': 'Eksamensform',
    'facts.exam.value': 'Løbende evaluering, gennemført uformelt',
    'facts.responsible': 'Kursusansvarlig',
    'facts.registration': 'Tilmelding',
    'facts.registration.value': 'Påkrævet. Antallet af pladser er begrænset af lokalets størrelse.',
    'facts.registration.link': 'Tilmeld dig her',
    'facts.deadline': 'Tilmeldingsfrist',

    'obj.heading': 'Læringsmål',
    'obj.intro': 'En studerende, der har opfyldt kursets mål, vil kunne:',
    'obj.1': 'Finde den rigtige indgang til bygningen i første forsøg',
    'obj.2': 'Lykønske værten uden at spørge, hvad specialet handlede om',
    'obj.3': 'Identificere mindst tre personer, som vedkommende aldrig har mødt før',
    'obj.4': 'Betjene en quiz under ikke ideelle forhold',
    'obj.5': 'Dokumentere aftenen fotografisk inden for den angivne grænse',
    'obj.6': 'Vurdere sin egen kapacitet korrekt og handle derefter',

    'enrol.heading': 'Tilmelding til kurset',
    'enrol.lede': 'Tilmelding er påkrævet. Ikke af bureaukratiske årsager, men fordi værten skal vide, hvor meget mad der skal købes.',
    'enrol.pending.title': 'Tilmelding åbner snart',
    'enrol.pending.body': 'Tilmeldingssystemet er ved at blive sat op. Kom tilbage om et par dage, eller sig det direkte til værten i mellemtiden.',

    'nudge.enrol.text': 'Du har ikke tilmeldt dig endnu.',
    'nudge.enrol.cta': 'Tilmeld dig',
    'nudge.enrol.soon': 'Tilmelding lukker om {n} dage.',
    'nudge.enrol.last': 'Tilmelding lukker i morgen.',
    'nudge.enrol.today': 'Tilmelding lukker i dag.',
    'nudge.group.text': 'Du er tilmeldt. Én ting mangler.',
    'nudge.group.cta': 'Kom med i gruppen',

    'wa.heading': 'Kursusmeddelelser',
    'wa.body': 'Praktiske opdateringer sendes i gruppechatten. Adresseændringer, forsinkelser og et enkelt billede i ny og næ.',
    'wa.cta': 'Kom med i WhatsApp gruppen',

    'loc.heading': 'Sted',
    'loc.lede': 'Undervisningen finder sted på adressen nedenfor. Ruten åbner i din egen kortapp.',
    'loc.pending.title': 'Lokale afventer bekræftelse',
    'loc.pending.body': 'Lokalebookingen forhandles stadig. Adressen vises her, så snart den ligger fast, og siden opdaterer sig selv.',
    'loc.address': 'Adresse',
    'loc.copy': 'Kopiér adresse',
    'loc.copied': 'Kopieret',
    'loc.copied.toast': 'Adressen er kopieret til udklipsholderen.',
    'loc.copy.failed': 'Kopiér den manuelt',
    'loc.copy.failed.toast': 'Kopiering blev blokeret af browseren. Adressen er nu markeret.',
    'loc.google': 'Åbn i Google Maps',
    'loc.apple': 'Åbn i Apple Maps',
    'loc.maptitle': 'Kort der viser festens placering',
    'loc.map.loading': 'Kortet indlæses. Adressen ovenfor virker også uden.',
    'loc.map.blocked': 'Kortet blev ikke indlæst. Brug adressen eller knapperne ovenfor.',

    'access.heading': 'Adgang til bygningen',
    'access.lede': 'Den mest nyttige sektion på denne side. Se den, før du ankommer, eller mens du står udenfor og tænker over, hvilken dør der er den rigtige.',
    'access.pending.title': 'Adgangsdokumentation undervejs',
    'access.pending.body': 'Et kort klip, der viser den rigtige dør, er under produktion. Indtil da kan du spørge den, der inviterede dig, eller følge lyden.',

    'photos.heading': 'Dokumentation',
    'photos.lede': 'Studerende bedes aflevere fotografisk dokumentation af aftenen. Maksimalt fem per person, en grænse valgt for at beskytte alle.',
    'photos.pending.title': 'Afleveringsportalen åbner senere',
    'photos.pending.body': 'Upload åbner tættere på datoen. Du skal ikke gøre noget nu.',

    'footer.disclaimer': 'En personlig invitation i den grafiske stil fra et universitet, som værten faktisk har gået på. Ikke tilknyttet, ikke godkendt af og på ingen måde det pågældende universitets ansvar.',
    'footer.built': 'Lavet til én aften i oktober.',
    'footer.lang': 'Sprog',

    'lang.it': 'Italiano',
    'lang.en': 'English',
    'lang.da': 'Dansk',
  },

};
